version: "1.1"
languages:
  lua:
    classes:
      ISLootWindowFloorControlHandler_TakeSameType:
        extends: ISLootWindowFloorControlHandler
        constructors:
          - {}
        staticFields:
          Type:
            defaultValue: '"ISLootWindowFloorControlHandler_TakeSameType"'
        fields:
          control: {}
          isMouseOver:
            type: boolean
          itemsToTransferMap:
            type: table
          inventoryContainerCount:
            type: number
        methods:
          - name: shouldBeVisible
            return:
              - type: boolean
          - name: getControl
            return:
              - type: unknown
          - name: perform
          - name: getItemsTable
            parameters:
              - name: container
            return:
              - type: table
          - name: getItemsToTransfer
            return:
              - type: table
              - type: table
          - name: onMouseOverButton
            parameters:
              - name: button
                type: ISButton
              - name: x
                type: number
              - name: y
                type: number
          - name: onMouseOutButton
            parameters:
              - name: button
                type: ISButton
              - name: dx
                type: number
              - name: dy
                type: number
          - name: wasInventoryUpdated
            return:
              - type: boolean
          - name: wasLootUpdated
            return:
              - type: boolean
