version: "1.1"
languages:
  lua:
    classes:
      ISLootWindowObjectControlHandler_PutOut:
        extends: ISLootWindowObjectControlHandler
        constructors:
          - {}
        staticFields:
          Type:
            defaultValue: '"ISLootWindowObjectControlHandler_PutOut"'
        fields:
          control: {}
        methods:
          - name: shouldBeVisible
            return:
              - type: boolean
          - name: getControl
            return:
              - type: unknown
          - name: handleJoypadContextMenu
            parameters:
              - name: context
                type: ISContextMenu
          - name: perform
